# app/config/security.yml
security:
    encoders:
       AppBundle\Entity\EconomicUser:
            algorithm: bcrypt
       AppBundle\Entity\AdminUser:
            algorithm: bcrypt     
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
        chain_provider:
            chain:
                providers: [admin_entity_provider, user_entity_provider]
        admin_entity_provider:
           entity:
                class: AppBundle:AdminUser
                property: username
        user_entity_provider:
            entity:
                class: AppBundle:EconomicUser
                property: username  
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin_secured_area:
            pattern: /admin/.*
            provider: admin_entity_provider
            anonymous: ~
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
                always_use_default_target_path: true
                default_target_path: /admin/index
            logout:
                path:   /admin/logout
                target: /admin/login
           
        economic_secured_area:
            pattern: /user/.*
            provider: user_entity_provider
            anonymous: ~
            form_login:
                check_path: /user/login_check
                login_path: /user/login
                always_use_default_target_path: true
                default_target_path: /user/index
            logout:
                path:   /user/logout
                target: /user/login
    access_control:
        admin_register:
            path: /admin/register
            roles: IS_AUTHENTICATED_ANONYMOUSLY
            requires_channel: https
            
        admin_create:
            path: /admin/register/create
            roles: IS_AUTHENTICATED_ANONYMOUSLY    
            requires_channel: https
        admin_login:
            path: /admin/login
            roles: IS_AUTHENTICATED_ANONYMOUSLY
            requires_channel: https
        admin_area:
            path: /admin/.*
            roles: ROLE_ADMIN
            requires_channel: https
        economic_register:
            path: /user/register
            roles: IS_AUTHENTICATED_ANONYMOUSLY
            requires_channel: https
        economic_create:
            path: /user/register/create
            roles: IS_AUTHENTICATED_ANONYMOUSLY
            requires_channel: https
        economic_login:
            path: /user/login
            roles: IS_AUTHENTICATED_ANONYMOUSLY
            requires_channel: https
        ecomomic_area:
            path: /user/.*
            roles: ROLE_USER
            requires_channel: https
    access_decision_manager:
        strategy: unanimous